### ISSUE TITLE
[Feature request] Identify Sysdig query templates that can be used in iter8 to create a Metrics resources

### ISSUE THREAD

**Issue by sushmarchandran** [iter8-tools/iter8-install#47]
**Is your feature request related to a problem? Please describe.**
Integration with domains such as code engine requires Sysdig metrics

**Describe the solution you'd like**
IBM Cloud documentation has information about using Sysdig metrics. Iter8 requires query templates for metrics such as mean latency, error rates, etc

**Acceptance criteria**
Metric configs for atleast 2 Sysdig metrics

**Additional context**
Sample Sysdig Query using curl:
`curl -X POST https://us-south.monitoring.cloud.ibm.com/api/data -H "Authorization: Bearer $SYSDIGTOKEN" -H "content-type: application/json" -d @metrics.json`
metrics.json:
```
{
  "last": 300,
  "metrics": [
    {
      "id": "ibm_codeengine_application_service_count"
    }
  ],
  "filter": "ibm_location = \"us-south\""
}
```

**Comment by sriumcp** [comment]
Done.
